<?php

/*
 * This file is part of the flarum-translations-builder.
 *
 * Copyright (c) 2019 Robert Korulczyk <robert@korulczyk.pl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

declare(strict_types=1);

namespace app\components\translations;

use Symfony\Component\Translation\Loader\ArrayLoader;
use Symfony\Component\Yaml\Yaml;
use Yii;
use function is_array;
use function is_string;

/**
 * Class YamlLoader.
 *
 * @author Robert Korulczyk <robert@korulczyk.pl>
 */
final class YamlLoader extends ArrayLoader {

	public $skipEmpty = false;

	public function __construct(array $config = []) {
		Yii::configure($this, $config);
	}

	public function load($resource, $locale, $domain = 'messages') {
		$messages = Yaml::parse($resource);
		$messages = self::filter($messages, explode("\n", $resource, 2)[0] . '...', $this->skipEmpty);
		return parent::load($messages, $locale, $domain);
	}

	public static function filter($item, string $resource, bool $skipEmpty = true) {
		if (!is_array($item)) {
			return $item;
		}

		foreach ($item as $key => $value) {
			if (is_array($value)) {
				$value = self::filter($value, $resource, $skipEmpty);
			} elseif (!is_string($value) && $value !== null) {
				$message = "Non-string translation occurred for '$key' key in '$resource'.";
				Yii::$app->frequencyLimiter->run(
					__METHOD__ . '#' . $message,
					31 * 24 * 3600,
					static function () use ($message) {
						Yii::warning($message, __CLASS__);
					}
				);
				$value = null;
			}

			if (
				$value === null || $value === [] || ($skipEmpty && $value === '')
				// These phrases come from extension template generated by Flarum CLI, and some extensions leave it
				// in that way even if they do not support translations at all.
				// @see https://github.com/flarum/cli/blob/v1.0.0/boilerplate/skeleton/extension/locale/en.yml
				|| ($key === 'my_cool_key' && $value === 'My Cool Key')
			) {
				unset($item[$key]);
			} else {
				$item[$key] = $value;
			}
		}

		return $item;
	}
}
