<?php

/*
 * This file is part of the flarum-translations-builder.
 *
 * Copyright (c) 2026 Robert Korulczyk <robert@korulczyk.pl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

declare(strict_types=1);

namespace app\components\inheritors;

use Dont\DontCall;
use Dont\DontCallStatic;
use Dont\DontGet;
use Dont\DontSet;
use function uasort;

/**
 * Generates navigation for all summaries generated by `InheritorDiffGenerator`.
 *
 * @author Robert Korulczyk <robert@korulczyk.pl>
 */
final class InheritorsSummaryGenerator {

	use DontCall;
	use DontCallStatic;
	use DontGet;
	use DontSet;

	/** @var array[] */
	private $reports = [];

	/**
	 * @param string $label Name of the inheritor, as it should be displayed in the summary.
	 * @param string $fileName Path of the report (or index of reports) relative to this summary.
	 * @param int $languagesCount Number of languages with any difference.
	 */
	public function addReport(
		InheritorInterface $inheritor,
		string $label,
		string $fileName,
		int $languagesCount,
		int $differencesCount,
		int $missingTranslationsCount
	): void {
		$this->reports[$inheritor->getId()] = [
			'label' => $label,
			'fileName' => $fileName,
			'inheritFromLabel' => $inheritor->getInheritFromLabel(),
			'languagesCount' => $languagesCount,
			'differencesCount' => $differencesCount,
			'missingTranslationsCount' => $missingTranslationsCount,
		];
	}

	public function generate(): string {
		$reports = $this->reports;
		uasort($reports, static function (array $a, array $b) {
			return $a['label'] <=> $b['label'];
		});

		$output = <<<MD
			# Inherited translations differences

			Translations for some languages are inherited from other languages or from other Flarum versions. 
			Inherited translations can be adjusted independently after inheritance, and reports below list all strings 
			which have the same source string on both sides, but do not match between them.

			| Inheritor | Inherited from | Languages | Different translations | Missing translations |
			| --- | --- | --- | --- | --- |

			MD;

		foreach ($reports as $report) {
			$output .= "| [{$report['label']}]({$report['fileName']}) "
				. "| {$report['inheritFromLabel']} "
				. "| {$report['languagesCount']} "
				. "| {$report['differencesCount']} "
				. "| {$report['missingTranslationsCount']} |\n";
		}

		return $output;
	}
}
