<?php

/*
 * This file is part of the flarum-translations-builder.
 *
 * Copyright (c) 2019 Robert Korulczyk <robert@korulczyk.pl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace app\models;

use app\components\readme\LanguageSubsplitReadmeGenerator;
use app\components\readme\ReadmeGenerator;
use app\components\translations\YamlFileDumper;
use Symfony\Component\Translation\Loader\ArrayLoader;
use Symfony\Component\Translation\Loader\JsonFileLoader;
use Symfony\Component\Translation\MessageCatalogue;
use Symfony\Component\Translation\Translator;
use function array_filter;
use function assert;
use function file_exists;

/**
 * Class LanguageSubsplit.
 *
 * @author Robert Korulczyk <robert@korulczyk.pl>
 */
final class LanguageSubsplit extends Subsplit {

	public const TYPE = 'language';

	private $language;

	public function __construct(
		string $id,
		string $language,
		string $repository,
		string $branch,
		string $path,
		?array $components,
		?bool $updateReadme = false
	) {
		$this->language = $language;

		parent::__construct($id, $repository, $branch, $path, $components, $updateReadme);
	}

	public function split(Translations $translations): void {
		$this->getRepository()->update();

		$components = [];
		$translator = new Translator('en');
		$translator->addLoader('json_file', new JsonFileLoader());
		$translator->addLoader('array', new ArrayLoader());

		foreach ($translations->getProjects() as $project) {
			// reverse array to process top record at the end - it will overwrite any previous translation
			foreach (array_reverse($project->getComponents()) as $component) {
				assert($component instanceof Component);
				if ($component->isValidForLanguage($this->language) && $this->isValidForComponent($project->getId(), $component->getId())) {
					$components[$component->getId()] = $components[$component->getId()] ?? $component;
					$translator->addResource(
						'json_file',
						$project->getComponentTranslationPath($component, $this->language),
						$this->language,
						$component->getId()
					);
				}
			}
		}

		$translationsCatalogue = $translator->getCatalogue($this->language);
		assert($translationsCatalogue instanceof MessageCatalogue);
		// add non-empty string from translations to sources
		foreach ($translations->getProjects() as $project) {
			// reverse array to process top record at the end - it will overwrite any previous translation
			foreach (array_reverse($project->getComponents()) as $component) {
				assert($component instanceof Component);
				if ($component->isValidForLanguage($this->language) && $this->isValidForComponent($project->getId(), $component->getId())) {
					$components[$component->getId()] = $components[$component->getId()] ?? $component;
					$messages = array_filter($translationsCatalogue->all($component->getId()), static function ($string) {
						return $string !== '';
					});

					if (!empty($messages)) {
						$translator->addResource('array', $messages, 'en', $component->getId());
					}
				}
			}
		}

		$dumper = new YamlFileDumper(function (string $id) use ($components, $translations) {
			$component = $components[$id];
			assert($component instanceof Component);
			$project = $translations->getProject($component->getProject());
			$url = "https://weblate.rob006.net/projects/{$project->getWeblateId()}/{$component->getId()}/{$this->language}/";

			return "# This file is automatically generated - do not edit it directly.\n"
				. "# Use $url for translation.\n"
				. "# You can read more about the process at https://github.com/rob006-software/flarum-translations/wiki.\n\n";
		});
		$dumper->setRelativePathTemplate('%domain%.%extension%');
		$sourcesCatalogue = $translator->getCatalogue('en');
		assert($sourcesCatalogue instanceof MessageCatalogue);
		$dumper->dump($sourcesCatalogue, [
			'path' => $this->getDir() . $this->getPath(),
			'as_tree' => true,
			'inline' => 10,
		]);
	}

	public function hasTranslationForComponent(string $componentId): bool {
		return file_exists($this->getDir() . $this->getPath() . "/$componentId.yml");
	}

	public function getLanguage(): string {
		return $this->language;
	}

	public function getReadmeGenerator(Translations $translations, Project $project): ReadmeGenerator {
		return new LanguageSubsplitReadmeGenerator($this->getLanguage(), $project, $translations->getVendors($project->getId()));
	}
}
